spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: dominik
    password: pirlo21
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: security_session
  redis:
    host: localhost
    port: 6379
logging:
  level:
    com.example.securityDemo: TRACE

server:
  servlet:
    session:
      timeout: 30
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*' #povoli vsetky endpointy actuator-a
  trace:
    http:
      include: PRINCIPAL, TIME_TAKEN, SESSION_ID, REQUEST_HEADERS, RESPONSE_HEADERS, COOKIE_HEADERS


